### ISSUE TITLE
Error: malformed ws or wss URL

### ISSUE THREAD

**Issue by t3db0t** [sosedoff/musicbot#5]
Howdy—trying to get this set up with my PiMusicBox.  I created a Slack application, but I wasn't sure what to put for `URL` and `Redirect URI(s)` so I just put the URL of our local MusicBox ("http://musicbox.local"—which doesn't really make sense to me but I'm not sure what else I would put...).  Anyway, I then run:

`./musicbot_darwin_amd64 --mopidy=musicbox.local --slack-token={client_secret}`

and get:

``````
2015/06/04 14:34:11 Connecting to Slack API...
2015/06/04 14:34:11 Connecting to Slack Websocket
2015/06/04 14:34:11 Error: malformed ws or wss URL
2015/06/04 14:34:11 malformed ws or wss URL```
``````

I can't tell if this is the result of one of my actions or not.  Thanks for any insight!

**Comment by t3db0t** [comment]
It may be the case that the "malformed ws" error is due to not specifying the Mopidy port...?  Trying to figure out what the default mopidy port is

**Comment by t3db0t** [comment]
Hm, when I do `--mopidy=http://musicbox.local:6680` I get `dial tcp: unknown port tcp/`

**Comment by sosedoff** [comment]
Here's where the url for mopidy ws/rpc gets constructed: https://github.com/sosedoff/musicbot/blob/master/mopidy/client.go#L31

So say you have your mopidy server running on 192.168.1.1:6680, then you should start bot with
`--mopidy=192.168.1.1:6680`. Let me know if that helps

**Comment by sosedoff** [comment]
Closing this for now

**Comment by smithamax** [comment]
Getting this issue too, `musicbot --debug --mopidy=localhost:6680 --slack-token='...'`

```
2015/06/23 11:46:11 Connecting to Slack API
2015/06/23 11:46:13 Connecting to Slack Websocket
2015/06/23 11:46:13 Error: malformed ws or wss URL
2015/06/23 11:46:13 malformed ws or wss URL
```

**Comment by baires** [comment]
Same issue here.
`musicbot --debug --mopidy=192.168.1.177:6680 --slack-token=TOKEN`

```
2016/04/21 13:50:50 Connecting to Slack API
2016/04/21 13:50:50 Connecting to Slack Websocket
2016/04/21 13:50:50 Error: malformed ws or wss URL
2016/04/21 13:50:50 malformed ws or wss URL
```

**Comment by sosedoff** [comment]
@baires is your mopidy server is correctly configured?
you can test if http server is running and ws endpoint is available with this command:

```
$ curl http://hostname:6680/mopidy/ws
Can "Upgrade" only to "WebSocket".
```

Although the error could be related to slack, i need to check it out.

**Comment by baires** [comment]
yup the http server is up:

``` bash
pi@raspberrypi:~ $ mopidy
INFO     Starting Mopidy 0.19.4
INFO     Loading config from: builtin defaults, /etc/xdg/mopidy/mopidy.conf, /home/pi/.config/mopidy/mopidy.conf, command line options
INFO     Enabled extensions: http, mpd, softwaremixer, local, stream
INFO     Disabled extensions: none
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Mixing using GStreamer software mixing
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: LocalBackend, StreamBackend
INFO     Loaded 0 local playlists from /home/pi/.local/share/mopidy/local/playlists
INFO     No local library metadata cache found at /home/pi/.local/share/mopidy/local/library.json.gz. Please run `mopidy local scan` to index your local music library. If you do not have a local music collection, you can disable the local backend to hide this message.
INFO     Loaded 0 local tracks using json
INFO     Audio output set to "autoaudiosink"
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::]:6600
INFO     HTTP server running at [::]:6680
```

And regarding to the ws endpoint it says:

``` bash
Can "Upgrade" only to "WebSocket"
```

**Comment by sosedoff** [comment]
It looks like you might have an invalid slack bot token. Make sure its a token for bot integration, not a slash command

**Comment by baires** [comment]
Yup, you were right. That fixed the issue with malformed url.
The  http server is running:

```
Received RPC message from 192.168.1.177: '{"jsonrpc":"2.0","method":"core.tracklist.clear","params":{},"id":8995016276575641803}'
```

But now I cant any song. 

```
DEBUG    2016-04-21 18:16:03,496 [3224:Core-5] mopidy.core.playback
  Triggering playback state change event
WARNING  2016-04-21 18:16:03,497 [3224:Core-5] mopidy.core.tracklist
  Track is not playable: spotify:track:0aym2LBJBk9DAYuHHutrIl
DEBUG    2016-04-21 18:16:03,497 [3224:MainThread] mopidy.listener
  Sending playback_state_changed to CoreListener: {'old_state': u'stopped', 'new_state': u'playing'}
DEBUG    2016-04-21 18:16:03,498 [3224:Core-5] mopidy.core.playback
  Changing state: playing -> stopped
```

Not sure if it an issue with musicbot or mopidy. Any hint on that?

Thanks for your time!

**Comment by sosedoff** [comment]
Hm, this could be on your end, ie mopidy configuration. Did you try testing mopidy via web interface like [moped](https://github.com/martijnboland/moped) ?

**Comment by baires** [comment]
Its working now, after some digging I realized that I was using a old version of Mopidy (0.19.xx I think). After upgrading to ver 2 and rebooting everything start working.

Kudos to you!
