### ISSUE TITLE
Make music bot not spotify sepcific?

### ISSUE THREAD

**Issue by addisonamiri** [sosedoff/musicbot#7]
I noticed on line 100 of musicbot/mopidy/commands.go you're specifying to only search spotify. Would there be any repercussions to removing that? I have a few other backends I would like to use as well. If musicbot is tightly integrated with spotify out of necessity then don't worry about it.

**Comment by sosedoff** [comment]
its tailored to spotify only as we use it to play music in the office. it could be used to play from any source, but i'll require some modifications.

**Comment by addisonamiri** [comment]
Would you rather pull requests if I make it more universal or should I just fork it?

**Comment by sosedoff** [comment]
If you're familiar with Go - please go ahead and submit PR

**Comment by addisonamiri** [comment]
I've never done anything in Go but I'll give this a shot. I've been itching to try it out lately.
