### ISSUE TITLE
command improvements

### ISSUE THREAD

**Issue by kballenegger** [sosedoff/musicbot#8]
It's not always ideal to add 10 tracks. It'd be nice to have some more powerful commands like:

```
skip 2 # skips two songs
search daft punk # shows search results
play 1-2 daft punk # plays first two songs for that search
```

Or something like that…

**Comment by baschny** [comment]
👍  good ideas, after one day of usage our team also noticed this exact problem

**Comment by sosedoff** [comment]
Sorry, i dont have any time to work on this project. If you wish to improve the functionality you can submit a PR.

**Comment by baschny** [comment]
@sosedoff thx for the feedback! my colleague just started a "new project" for that purposes in a language that we are more familiar with (NodeJS).

**Comment by baschny** [comment]
See: https://github.com/100hz/dopebot
